# Generated by Django 5.0.1 on 2024-02-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
